ibtikar_glance_ums_staff:
    resource: "@IbtikarGlanceUMSBundle/Resources/config/staff.yml"
    prefix:   /backend

ibtikar_glance_ums_visitor:
    resource: "@IbtikarGlanceUMSBundle/Resources/config/visitor.yml"
    prefix:   /

ibtikar_glance_ums_city:
    resource: "@IbtikarGlanceUMSBundle/Resources/config/city.yml"
    prefix:   /backend/city

ibtikar_glance_ums_job:
    resource: "@IbtikarGlanceUMSBundle/Resources/config/job.yml"
    prefix:   /backend/job

ibtikar_glance_ums_role:
    resource: "@IbtikarGlanceUMSBundle/Resources/config/role.yml"
    prefix:   /backend/role


login:
    path:  /login
    defaults: { _controller: IbtikarGlanceUMSBundle:Visitor:login }
    schemes:  [%httpProtocol%]

login_check:
    path:  /login-check

post_login:
    path:  /post-login
    defaults: { _controller: IbtikarGlanceUMSBundle:User:postLogin }
    schemes:  [%httpProtocol%]

logout:
    path:  /logout

access_denied:
    path:  /access-denied
    defaults: { _controller: IbtikarGlanceUMSBundle:User:accessDenied }