parameters:
#    security.authentication.listener.form.class: Ibtikar\UserBundle\Listener\PreLogin
    captcha_appear_after_failed_attempts: 3
services:
#    ibtikar_user.example:
#        class: Ibtikar\GlanceUMSBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
#    ajax_listener:
#        class: Ibtikar\GlanceUMSBundle\Listener\AjaxAuthenticationListener
#        tags:
#          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 255 }
#        arguments: ["@router","@session","@translator"]
#
#    Ibtikar.security.authentication_failure_event_listener:
#      class: Ibtikar\GlanceUMSBundle\Listener\AuthenticationListener
#      tags:
#          - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
#      arguments: ["@session"]
#    # authentication success event listener
#    Ibtikar.security.interactive_login_listener:
#        class: Ibtikar\GlanceUMSBundle\Listener\AuthenticationListener
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }
#        arguments: ["@session"]
#
#    content_length_listener:
#        class: Ibtikar\GlanceUMSBundle\Listener\ContentLengthListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: onResponse, priority: -255 }
#        arguments: ["@service_container"]
#
#    request.listener.update_user_last_seen:
#        class: Ibtikar\GlanceUMSBundle\Listener\UpdateUserLastSeenListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
#        arguments: ["@security.authorization_checker", "@doctrine_mongodb"]

    logout_handler:
        class: Ibtikar\GlanceUMSBundle\Listener\LogoutHandler
        arguments: ["@service_container"]
