# also edit the route path in the user login action
ibtikar_glance_ums_staff_login:
    path:  /login
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:login }
    schemes:  [%httpProtocol%]

ibtikar_glance_ums_staff_forgot_password:
    path:  /forgot-password
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:forgotPassword }

ibtikar_glance_ums_staff_changePassword:
    path:  /change-password
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:changePassword }
    schemes:  [%httpProtocol%]

ibtikar_glance_ums_staff_change_password_from_email:
    path:  /change-password-email/{email}/{token}
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:changePasswordFromEmail }
    schemes:  [%httpProtocol%]

ibtikar_glance_ums_staff_create:
    path: /staff/create
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:create }

ibtikar_glance_ums_staff_edit:
    path: /staff/edit/{id}
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:edit ,id: id}

ibtikar_glance_ums_staff_delete:
    path: /staff/delete/{id}
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:delete ,id: id}

ibtikar_glance_ums_staff_check_field_unique:
    path: /staff/checkfieldUnique
    defaults: { _controller: IbtikarGlanceUMSBundle:User:checkFieldUnique }

ibtikar_glance_ums_staff_change_list_columns:
    path:  /staff/change-list-columns
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:changeListColumns }

ibtikar_glance_ums_staff_list:
    path:  /staff/list
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:list }

ibtikar_glance_ums_staff_delete_image:
    path:  /staff/remove/image/{id}
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:deleteImage }

ibtikar_glance_ums_staff_bulk_actions:
    path: /staff/bulk
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:bulk}
