# also edit the route path in the user login action
ibtikar_glance_ums_staff_login:
    path:  /login
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:login }
    schemes:  [%httpProtocol%]

ibtikar_glance_ums_staff_contact:
    path:  /contact
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:contact }

ibtikar_glance_ums_staff_forgot_password:
    path:  /forgot-password
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:forgotPassword }

ibtikar_glance_ums_staff_changePassword:
    path:  /change-password
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:changePassword }
    schemes:  [%httpProtocol%]

ibtikar_glance_ums_staff_change_password_from_email:
    path:  /change-password-email/{email}/{token}
    defaults: { _controller: IbtikarGlanceUMSBundle:Staff:changePasswordFromEmail }
    schemes:  [%httpProtocol%]
