<?php

namespace Ibtikar\GlanceUMSBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Ibtikar\GlanceDashboardBundle\Service\ArabicMongoRegex;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends DocumentRepository {

    /**
     * Finds documents by a set of criteria.
     * @author Mahmoud Mostafa <mahmoud.mostafa@ibtikar.net.sa>
     * @param array        $criteria Query criteria
     * @param array        $sort     Sort array for Cursor::sort()
     * @param integer|null $limit    Limit for Cursor::limit()
     * @param integer|null $skip     Skip for Cursor::skip()
     *
     * @return array
     */
    public function findBy(array $criteria, array $sort = null, $limit = null, $skip = null) {
        if(isset($criteria['name'])) {
            $criteria['name'] = new \MongoRegex(ArabicMongoRegex::getExactStringRegex($criteria['name']));
        }
        if(isset($criteria['name_en'])) {
            $criteria['name_en'] = new \MongoRegex('/^' . $criteria['name_en'] . '$/');
        }
        return parent::findBy($criteria, $sort, $limit, $skip);
    }

    /**
     * @author Mahmoud Mostafa <mahmoud.mostafa@ibtikar.net.sa>
     * @param string $countryId
     * @return string
     */
    public function getCountryCitiesThatHasNewsAndLocation($countryId) {
        return $this->findBy(array(
                    'country' => $countryId,
                    'long' => array(
                        '$exists' => true
                    ),
                    'lat' => array(
                        '$exists' => true
                    )
        ));
    }

}
