<?php

namespace Ibtikar\GlanceUMSBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends DocumentRepository {

}
